#!/usr/bin/env bash
# Configure Nginx server for redirection

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.goal.com/en permanent;' /etc/nginx/sites-available/default
service nginx start
