#!/usr/bin/env bash
# Configure web-02 to be identical to web-01

ADD301_REDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"
ADD404_NOTFOUND="error_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\t root /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
PATTERN="#error_page 404 /404.html;"
ADD_HEADER="\\\tadd_header X-Served-By $HOSTNAME;"

apt-get -y update
apt-get -y install nginx
service start nginx

echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html

sed -i "30i $ADD301_REDIRECT" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

sed -i "s@$PATTERN@$ADD404_NOTFOUND@" /etc/nginx/sites-available/default

sed -i "27i $ADD_HEADER" /etc/nginx/sites-available/default

service nginx start
