#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with requirements below

cp /etc/hosts hosts_temp
sed -i s/127.*$/127.0.0.2\\tlocalhost\\n8.8.8.8\\tfacebook.com/g hosts_temp
cp -f hosts_temp /etc/hosts
