#!/usr/bin/env bash
# SSH client configuration

Host *
     passwordAuthentication no
     IdentifyFile ~/.ssh/school
     SendEnv LANG LC_*
     HashKnownHosts yes
     GSSAPIAuthentication yes
     GSSAPIDelegateCredentials no
